export const countries = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'AndorrA', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People'S Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'RWANDA', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia and Montenegro', code: 'CS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];

export const indianStatesWithCities = {
  'Andaman and Nicobar Islands': ['Port Blair'],
  Haryana: [
    'Faridabad',
    'Gurgaon',
    'Hisar',
    'Rohtak',
    'Panipat',
    'Karnal',
    'Sonipat',
    'Yamunanagar',
    'Panchkula',
    'Bhiwani',
    'Bahadurgarh',
    'Jind',
    'Sirsa',
    'Thanesar',
    'Kaithal',
    'Palwal',
    'Rewari',
    'Hansi',
    'Narnaul',
    'Fatehabad',
    'Gohana',
    'Tohana',
    'Narwana',
    'Mandi Dabwali',
    'Charkhi Dadri',
    'Shahbad',
    'Pehowa',
    'Samalkha',
    'Pinjore',
    'Ladwa',
    'Sohna',
    'Safidon',
    'Taraori',
    'Mahendragarh',
    'Ratia',
    'Rania',
    'Sarsod',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tirunelveli',
    'Tiruppur',
    'Ranipet',
    'Nagercoil',
    'Thanjavur',
    'Vellore',
    'Kancheepuram',
    'Erode',
    'Tiruvannamalai',
    'Pollachi',
    'Rajapalayam',
    'Sivakasi',
    'Pudukkottai',
    'Neyveli (TS)',
    'Nagapattinam',
    'Viluppuram',
    'Tiruchengode',
    'Vaniyambadi',
    'Theni Allinagaram',
    'Udhagamandalam',
    'Aruppukkottai',
    'Paramakudi',
    'Arakkonam',
    'Virudhachalam',
    'Srivilliputhur',
    'Tindivanam',
    'Virudhunagar',
    'Karur',
    'Valparai',
    'Sankarankovil',
    'Tenkasi',
    'Palani',
    'Pattukkottai',
    'Tirupathur',
    'Ramanathapuram',
    'Udumalaipettai',
    'Gobichettipalayam',
    'Thiruvarur',
    'Thiruvallur',
    'Panruti',
    'Namakkal',
    'Thirumangalam',
    'Vikramasingapuram',
    'Nellikuppam',
    'Rasipuram',
    'Tiruttani',
    'Nandivaram-Guduvancheri',
    'Periyakulam',
    'Pernampattu',
    'Vellakoil',
    'Sivaganga',
    'Vadalur',
    'Rameshwaram',
    'Tiruvethipuram',
    'Perambalur',
    'Usilampatti',
    'Vedaranyam',
    'Sathyamangalam',
    'Puliyankudi',
    'Nanjikottai',
    'Thuraiyur',
    'Sirkali',
    'Tiruchendur',
    'Periyasemur',
    'Sattur',
    'Vandavasi',
    'Tharamangalam',
    'Tirukkoyilur',
    'Oddanchatram',
    'Palladam',
    'Vadakkuvalliyur',
    'Tirukalukundram',
    'Uthamapalayam',
    'Surandai',
    'Sankari',
    'Shenkottai',
    'Vadipatti',
    'Sholingur',
    'Tirupathur',
    'Manachanallur',
    'Viswanatham',
    'Polur',
    'Panagudi',
    'Uthiramerur',
    'Thiruthuraipoondi',
    'Pallapatti',
    'Ponneri',
    'Lalgudi',
    'Natham',
    'Unnamalaikadai',
    'P.N.Patti',
    'Tharangambadi',
    'Tittakudi',
    'Pacode',
    "O' Valley",
    'Suriyampalayam',
    'Sholavandan',
    'Thammampatti',
    'Namagiripettai',
    'Peravurani',
    'Parangipettai',
    'Pudupattinam',
    'Pallikonda',
    'Sivagiri',
    'Punjaipugalur',
    'Padmanabhapuram',
    'Thirupuvanam',
  ],
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Ratlam',
    'Satna',
    'Murwara (Katni)',
    'Morena',
    'Singrauli',
    'Rewa',
    'Vidisha',
    'Ganjbasoda',
    'Shivpuri',
    'Mandsaur',
    'Neemuch',
    'Nagda',
    'Itarsi',
    'Sarni',
    'Sehore',
    'Mhow Cantonment',
    'Seoni',
    'Balaghat',
    'Ashok Nagar',
    'Tikamgarh',
    'Shahdol',
    'Pithampur',
    'Alirajpur',
    'Mandla',
    'Sheopur',
    'Shajapur',
    'Panna',
    'Raghogarh-Vijaypur',
    'Sendhwa',
    'Sidhi',
    'Pipariya',
    'Shujalpur',
    'Sironj',
    'Pandhurna',
    'Nowgong',
    'Mandideep',
    'Sihora',
    'Raisen',
    'Lahar',
    'Maihar',
    'Sanawad',
    'Sabalgarh',
    'Umaria',
    'Porsa',
    'Narsinghgarh',
    'Malaj Khand',
    'Sarangpur',
    'Mundi',
    'Nepanagar',
    'Pasan',
    'Mahidpur',
    'Seoni-Malwa',
    'Rehli',
    'Manawar',
    'Rahatgarh',
    'Panagar',
    'Wara Seoni',
    'Tarana',
    'Sausar',
    'Rajgarh',
    'Niwari',
    'Mauganj',
    'Manasa',
    'Nainpur',
    'Prithvipur',
    'Sohagpur',
    'Nowrozabad (Khodargama)',
    'Shamgarh',
    'Maharajpur',
    'Multai',
    'Pali',
    'Pachore',
    'Rau',
    'Mhowgaon',
    'Vijaypur',
    'Narsinghgarh',
  ],
  Jharkhand: [
    'Dhanbad',
    'Ranchi',
    'Jamshedpur',
    'Bokaro Steel City',
    'Deoghar',
    'Phusro',
    'Adityapur',
    'Hazaribag',
    'Giridih',
    'Ramgarh',
    'Jhumri Tilaiya',
    'Saunda',
    'Sahibganj',
    'Medininagar (Daltonganj)',
    'Chaibasa',
    'Chatra',
    'Gumia',
    'Dumka',
    'Madhupur',
    'Chirkunda',
    'Pakaur',
    'Simdega',
    'Musabani',
    'Mihijam',
    'Patratu',
    'Lohardaga',
    'Tenu dam-cum-Kathhara',
  ],
  Mizoram: ['Aizawl', 'Lunglei', 'Saiha'],
  Nagaland: [
    'Dimapur',
    'Kohima',
    'Zunheboto',
    'Tuensang',
    'Wokha',
    'Mokokchung',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Mandi',
    'Solan',
    'Nahan',
    'Sundarnagar',
    'Palampur',
    'Kullu',
  ],
  Tripura: [
    'Agartala',
    'Udaipur',
    'Dharmanagar',
    'Pratapgarh',
    'Kailasahar',
    'Belonia',
    'Khowai',
  ],
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Kakinada',
    'Tirupati',
    'Anantapur',
    'Kadapa',
    'Vizianagaram',
    'Eluru',
    'Ongole',
    'Nandyal',
    'Machilipatnam',
    'Adoni',
    'Tenali',
    'Chittoor',
    'Hindupur',
    'Proddatur',
    'Bhimavaram',
    'Madanapalle',
    'Guntakal',
    'Dharmavaram',
    'Gudivada',
    'Srikakulam',
    'Narasaraopet',
    'Rajampet',
    'Tadpatri',
    'Tadepalligudem',
    'Chilakaluripet',
    'Yemmiganur',
    'Kadiri',
    'Chirala',
    'Anakapalle',
    'Kavali',
    'Palacole',
    'Sullurpeta',
    'Tanuku',
    'Rayachoti',
    'Srikalahasti',
    'Bapatla',
    'Naidupet',
    'Nagari',
    'Gudur',
    'Vinukonda',
    'Narasapuram',
    'Nuzvid',
    'Markapur',
    'Ponnur',
    'Kandukur',
    'Bobbili',
    'Rayadurg',
    'Samalkot',
    'Jaggaiahpet',
    'Tuni',
    'Amalapuram',
    'Bheemunipatnam',
    'Venkatagiri',
    'Sattenapalle',
    'Pithapuram',
    'Palasa Kasibugga',
    'Parvathipuram',
    'Macherla',
    'Gooty',
    'Salur',
    'Mandapeta',
    'Jammalamadugu',
    'Peddapuram',
    'Punganur',
    'Nidadavole',
    'Repalle',
    'Ramachandrapuram',
    'Kovvur',
    'Tiruvuru',
    'Uravakonda',
    'Narsipatnam',
    'Yerraguntla',
    'Pedana',
    'Puttur',
    'Renigunta',
    'Rajam',
    'Srisailam Project (Right Flank Colony) Township',
  ],
  Punjab: [
    'Ludhiana',
    'Patiala',
    'Amritsar',
    'Jalandhar',
    'Bathinda',
    'Pathankot',
    'Hoshiarpur',
    'Batala',
    'Moga',
    'Malerkotla',
    'Khanna',
    'Mohali',
    'Barnala',
    'Firozpur',
    'Phagwara',
    'Kapurthala',
    'Zirakpur',
    'Kot Kapura',
    'Faridkot',
    'Muktsar',
    'Rajpura',
    'Sangrur',
    'Fazilka',
    'Gurdaspur',
    'Kharar',
    'Gobindgarh',
    'Mansa',
    'Malout',
    'Nabha',
    'Tarn Taran',
    'Jagraon',
    'Sunam',
    'Dhuri',
    'Firozpur Cantt.',
    'Sirhind Fatehgarh Sahib',
    'Rupnagar',
    'Jalandhar Cantt.',
    'Samana',
    'Nawanshahr',
    'Rampura Phul',
    'Nangal',
    'Nakodar',
    'Zira',
    'Patti',
    'Raikot',
    'Longowal',
    'Urmar Tanda',
    'Morinda, India',
    'Phillaur',
    'Pattran',
    'Qadian',
    'Sujanpur',
    'Mukerian',
    'Talwara',
  ],
  Chandigarh: ['Chandigarh'],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Bikaner',
    'Udaipur',
    'Ajmer',
    'Bhilwara',
    'Alwar',
    'Bharatpur',
    'Pali',
    'Barmer',
    'Sikar',
    'Tonk',
    'Sadulpur',
    'Sawai Madhopur',
    'Nagaur',
    'Makrana',
    'Sujangarh',
    'Sardarshahar',
    'Ladnu',
    'Ratangarh',
    'Nokha',
    'Nimbahera',
    'Suratgarh',
    'Rajsamand',
    'Lachhmangarh',
    'Rajgarh (Churu)',
    'Nasirabad',
    'Nohar',
    'Phalodi',
    'Nathdwara',
    'Pilani',
    'Merta City',
    'Sojat',
    'Neem-Ka-Thana',
    'Sirohi',
    'Pratapgarh',
    'Rawatbhata',
    'Sangaria',
    'Lalsot',
    'Pilibanga',
    'Pipar City',
    'Taranagar',
    'Vijainagar, Ajmer',
    'Sumerpur',
    'Sagwara',
    'Ramganj Mandi',
    'Lakheri',
    'Udaipurwati',
    'Losal',
    'Sri Madhopur',
    'Ramngarh',
    'Rawatsar',
    'Rajakhera',
    'Shahpura',
    'Shahpura',
    'Raisinghnagar',
    'Malpura',
    'Nadbai',
    'Sanchore',
    'Nagar',
    'Rajgarh (Alwar)',
    'Sheoganj',
    'Sadri',
    'Todaraisingh',
    'Todabhim',
    'Reengus',
    'Rajaldesar',
    'Sadulshahar',
    'Sambhar',
    'Prantij',
    'Mount Abu',
    'Mangrol',
    'Phulera',
    'Mandawa',
    'Pindwara',
    'Mandalgarh',
    'Takhatgarh',
  ],
  Assam: [
    'Guwahati',
    'Silchar',
    'Dibrugarh',
    'Nagaon',
    'Tinsukia',
    'Jorhat',
    'Bongaigaon City',
    'Dhubri',
    'Diphu',
    'North Lakhimpur',
    'Tezpur',
    'Karimganj',
    'Sibsagar',
    'Goalpara',
    'Barpeta',
    'Lanka',
    'Lumding',
    'Mankachar',
    'Nalbari',
    'Rangia',
    'Margherita',
    'Mangaldoi',
    'Silapathar',
    'Mariani',
    'Marigaon',
  ],
  Odisha: [
    'Bhubaneswar',
    'Cuttack',
    'Raurkela',
    'Brahmapur',
    'Sambalpur',
    'Puri',
    'Baleshwar Town',
    'Baripada Town',
    'Bhadrak',
    'Balangir',
    'Jharsuguda',
    'Bargarh',
    'Paradip',
    'Bhawanipatna',
    'Dhenkanal',
    'Barbil',
    'Kendujhar',
    'Sunabeda',
    'Rayagada',
    'Jatani',
    'Byasanagar',
    'Kendrapara',
    'Rajagangapur',
    'Parlakhemundi',
    'Talcher',
    'Sundargarh',
    'Phulabani',
    'Pattamundai',
    'Titlagarh',
    'Nabarangapur',
    'Soro',
    'Malkangiri',
    'Rairangpur',
    'Tarbha',
  ],
  Chhattisgarh: [
    'Raipur',
    'Bhilai Nagar',
    'Korba',
    'Bilaspur',
    'Durg',
    'Rajnandgaon',
    'Jagdalpur',
    'Raigarh',
    'Ambikapur',
    'Mahasamund',
    'Dhamtari',
    'Chirmiri',
    'Bhatapara',
    'Dalli-Rajhara',
    'Naila Janjgir',
    'Tilda Newra',
    'Mungeli',
    'Manendragarh',
    'Sakti',
  ],
  'Jammu and Kashmir': [
    'Srinagar',
    'Jammu',
    'Baramula',
    'Anantnag',
    'Sopore',
    'KathUrban Agglomeration',
    'Rajauri',
    'Punch',
    'Udhampur',
  ],
  Karnataka: [
    'Bengaluru',
    'Hubli-Dharwad',
    'Belagavi',
    'Mangaluru',
    'Davanagere',
    'Ballari',
    'Mysore',
    'Tumkur',
    'Shivamogga',
    'Raayachuru',
    'Robertson Pet',
    'Kolar',
    'Mandya',
    'Udupi',
    'Chikkamagaluru',
    'Karwar',
    'Ranebennuru',
    'Ranibennur',
    'Ramanagaram',
    'Gokak',
    'Yadgir',
    'Rabkavi Banhatti',
    'Shahabad',
    'Sirsi',
    'Sindhnur',
    'Tiptur',
    'Arsikere',
    'Nanjangud',
    'Sagara',
    'Sira',
    'Puttur',
    'Athni',
    'Mulbagal',
    'Surapura',
    'Siruguppa',
    'Mudhol',
    'Sidlaghatta',
    'Shahpur',
    'Saundatti-Yellamma',
    'Wadi',
    'Manvi',
    'Nelamangala',
    'Lakshmeshwar',
    'Ramdurg',
    'Nargund',
    'Tarikere',
    'Malavalli',
    'Savanur',
    'Lingsugur',
    'Vijayapura',
    'Sankeshwara',
    'Madikeri',
    'Talikota',
    'Sedam',
    'Shikaripur',
    'Mahalingapura',
    'Mudalagi',
    'Muddebihal',
    'Pavagada',
    'Malur',
    'Sindhagi',
    'Sanduru',
    'Afzalpur',
    'Maddur',
    'Madhugiri',
    'Tekkalakote',
    'Terdal',
    'Mudabidri',
    'Magadi',
    'Navalgund',
    'Shiggaon',
    'Shrirangapattana',
    'Sindagi',
    'Sakaleshapura',
    'Srinivaspur',
    'Ron',
    'Mundargi',
    'Sadalagi',
    'Piriyapatna',
    'Adyar',
  ],
  Manipur: ['Imphal', 'Thoubal', 'Lilong', 'Mayang Imphal'],
  Kerala: [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Kollam',
    'Thrissur',
    'Palakkad',
    'Alappuzha',
    'Malappuram',
    'Ponnani',
    'Vatakara',
    'Kanhangad',
    'Taliparamba',
    'Koyilandy',
    'Neyyattinkara',
    'Kayamkulam',
    'Nedumangad',
    'Kannur',
    'Tirur',
    'Kottayam',
    'Kasaragod',
    'Kunnamkulam',
    'Ottappalam',
    'Thiruvalla',
    'Thodupuzha',
    'Chalakudy',
    'Changanassery',
    'Punalur',
    'Nilambur',
    'Cherthala',
    'Perinthalmanna',
    'Mattannur',
    'Shoranur',
    'Varkala',
    'Paravoor',
    'Pathanamthitta',
    'Peringathur',
    'Attingal',
    'Kodungallur',
    'Pappinisseri',
    'Chittur-Thathamangalam',
    'Muvattupuzha',
    'Adoor',
    'Mavelikkara',
    'Mavoor',
    'Perumbavoor',
    'Vaikom',
    'Palai',
    'Panniyannur',
    'Guruvayoor',
    'Puthuppally',
    'Panamattom',
  ],
  Delhi: ['Delhi', 'New Delhi'],
  'Dadra and Nagar Haveli': ['Silvassa'],
  Puducherry: ['Pondicherry', 'Karaikal', 'Yanam', 'Mahe'],
  Uttarakhand: [
    'Dehradun',
    'Hardwar',
    'Haldwani-cum-Kathgodam',
    'Srinagar',
    'Kashipur',
    'Roorkee',
    'Rudrapur',
    'Rishikesh',
    'Ramnagar',
    'Pithoragarh',
    'Manglaur',
    'Nainital',
    'Mussoorie',
    'Tehri',
    'Pauri',
    'Nagla',
    'Sitarganj',
    'Bageshwar',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Firozabad',
    'Agra',
    'Meerut',
    'Varanasi',
    'Allahabad',
    'Amroha',
    'Moradabad',
    'Aligarh',
    'Saharanpur',
    'Noida',
    'Loni',
    'Jhansi',
    'Shahjahanpur',
    'Rampur',
    'Modinagar',
    'Hapur',
    'Etawah',
    'Sambhal',
    'Orai',
    'Bahraich',
    'Unnao',
    'Rae Bareli',
    'Lakhimpur',
    'Sitapur',
    'Lalitpur',
    'Pilibhit',
    'Chandausi',
    'Hardoi ',
    'Azamgarh',
    'Khair',
    'Sultanpur',
    'Tanda',
    'Nagina',
    'Shamli',
    'Najibabad',
    'Shikohabad',
    'Sikandrabad',
    'Shahabad, Hardoi',
    'Pilkhuwa',
    'Renukoot',
    'Vrindavan',
    'Ujhani',
    'Laharpur',
    'Tilhar',
    'Sahaswan',
    'Rath',
    'Sherkot',
    'Kalpi',
    'Tundla',
    'Sandila',
    'Nanpara',
    'Sardhana',
    'Nehtaur',
    'Seohara',
    'Padrauna',
    'Mathura',
    'Thakurdwara',
    'Nawabganj',
    'Siana',
    'Noorpur',
    'Sikandra Rao',
    'Puranpur',
    'Rudauli',
    'Thana Bhawan',
    'Palia Kalan',
    'Zaidpur',
    'Nautanwa',
    'Zamania',
    'Shikarpur, Bulandshahr',
    'Naugawan Sadat',
    'Fatehpur Sikri',
    'Shahabad, Rampur',
    'Robertsganj',
    'Utraula',
    'Sadabad',
    'Rasra',
    'Lar',
    'Lal Gopalganj Nindaura',
    'Sirsaganj',
    'Pihani',
    'Shamsabad, Agra',
    'Rudrapur',
    'Soron',
    'SUrban Agglomerationr',
    'Samdhan',
    'Sahjanwa',
    'Rampur Maniharan',
    'Sumerpur',
    'Shahganj',
    'Tulsipur',
    'Tirwaganj',
    'PurqUrban Agglomerationzi',
    'Shamsabad, Farrukhabad',
    'Warhapur',
    'Powayan',
    'Sandi',
    'Achhnera',
    'Naraura',
    'Nakur',
    'Sahaspur',
    'Safipur',
    'Reoti',
    'Sikanderpur',
    'Saidpur',
    'Sirsi',
    'Purwa',
    'Parasi',
    'Lalganj',
    'Phulpur',
    'Shishgarh',
    'Sahawar',
    'Samthar',
    'Pukhrayan',
    'Obra',
    'Niwai',
    'Mirzapur',
  ],
  Bihar: [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Darbhanga',
    'Arrah',
    'Begusarai',
    'Chhapra',
    'Katihar',
    'Munger',
    'Purnia',
    'Saharsa',
    'Sasaram',
    'Hajipur',
    'Dehri-on-Sone',
    'Bettiah',
    'Motihari',
    'Bagaha',
    'Siwan',
    'Kishanganj',
    'Jamalpur',
    'Buxar',
    'Jehanabad',
    'Aurangabad',
    'Lakhisarai',
    'Nawada',
    'Jamui',
    'Sitamarhi',
    'Araria',
    'Gopalganj',
    'Madhubani',
    'Masaurhi',
    'Samastipur',
    'Mokameh',
    'Supaul',
    'Dumraon',
    'Arwal',
    'Forbesganj',
    'BhabUrban Agglomeration',
    'Narkatiaganj',
    'Naugachhia',
    'Madhepura',
    'Sheikhpura',
    'Sultanganj',
    'Raxaul Bazar',
    'Ramnagar',
    'Mahnar Bazar',
    'Warisaliganj',
    'Revelganj',
    'Rajgir',
    'Sonepur',
    'Sherghati',
    'Sugauli',
    'Makhdumpur',
    'Maner',
    'Rosera',
    'Nokha',
    'Piro',
    'Rafiganj',
    'Marhaura',
    'Mirganj',
    'Lalganj',
    'Murliganj',
    'Motipur',
    'Manihari',
    'Sheohar',
    'Maharajganj',
    'Silao',
    'Barh',
    'Asarganj',
  ],
  Gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Nadiad',
    'Porbandar',
    'Anand',
    'Morvi',
    'Mahesana',
    'Bharuch',
    'Vapi',
    'Navsari',
    'Veraval',
    'Bhuj',
    'Godhra',
    'Palanpur',
    'Valsad',
    'Patan',
    'Deesa',
    'Amreli',
    'Anjar',
    'Dhoraji',
    'Khambhat',
    'Mahuva',
    'Keshod',
    'Wadhwan',
    'Ankleshwar',
    'Savarkundla',
    'Kadi',
    'Visnagar',
    'Upleta',
    'Una',
    'Sidhpur',
    'Unjha',
    'Mangrol',
    'Viramgam',
    'Modasa',
    'Palitana',
    'Petlad',
    'Kapadvanj',
    'Sihor',
    'Wankaner',
    'Limbdi',
    'Mandvi',
    'Thangadh',
    'Vyara',
    'Padra',
    'Lunawada',
    'Rajpipla',
    'Vapi',
    'Umreth',
    'Sanand',
    'Rajula',
    'Radhanpur',
    'Mahemdabad',
    'Ranavav',
    'Tharad',
    'Mansa',
    'Umbergaon',
    'Talaja',
    'Vadnagar',
    'Manavadar',
    'Salaya',
    'Vijapur',
    'Pardi',
    'Rapar',
    'Songadh',
    'Lathi',
    'Adalaj',
    'Chhapra',
    'Gandhinagar',
  ],
  Telangana: [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Karimnagar',
    'Ramagundam',
    'Khammam',
    'Mahbubnagar',
    'Mancherial',
    'Adilabad',
    'Suryapet',
    'Jagtial',
    'Miryalaguda',
    'Nirmal',
    'Kamareddy',
    'Kothagudem',
    'Bodhan',
    'Palwancha',
    'Mandamarri',
    'Koratla',
    'Sircilla',
    'Tandur',
    'Siddipet',
    'Wanaparthy',
    'Kagaznagar',
    'Gadwal',
    'Sangareddy',
    'Bellampalle',
    'Bhongir',
    'Vikarabad',
    'Jangaon',
    'Bhadrachalam',
    'Bhainsa',
    'Farooqnagar',
    'Medak',
    'Narayanpet',
    'Sadasivpet',
    'Yellandu',
    'Manuguru',
    'Kyathampalle',
    'Nagarkurnool',
  ],
  Meghalaya: ['Shillong', 'Tura', 'Nongstoin'],
  'Himachal Praddesh': ['Manali'],
  'Arunachal Pradesh': ['Naharlagun', 'Pasighat'],
  Maharashtra: [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Kalyan-Dombivali',
    'Vasai-Virar',
    'Solapur',
    'Mira-Bhayandar',
    'Bhiwandi',
    'Amravati',
    'Nanded-Waghala',
    'Sangli',
    'Malegaon',
    'Akola',
    'Latur',
    'Dhule',
    'Ahmednagar',
    'Ichalkaranji',
    'Parbhani',
    'Panvel',
    'Yavatmal',
    'Achalpur',
    'Osmanabad',
    'Nandurbar',
    'Satara',
    'Wardha',
    'Udgir',
    'Aurangabad',
    'Amalner',
    'Akot',
    'Pandharpur',
    'Shrirampur',
    'Parli',
    'Washim',
    'Ambejogai',
    'Manmad',
    'Ratnagiri',
    'Uran Islampur',
    'Pusad',
    'Sangamner',
    'Shirpur-Warwade',
    'Malkapur',
    'Wani',
    'Lonavla',
    'Talegaon Dabhade',
    'Anjangaon',
    'Umred',
    'Palghar',
    'Shegaon',
    'Ozar',
    'Phaltan',
    'Yevla',
    'Shahade',
    'Vita',
    'Umarkhed',
    'Warora',
    'Pachora',
    'Tumsar',
    'Manjlegaon',
    'Sillod',
    'Arvi',
    'Nandura',
    'Vaijapur',
    'Wadgaon Road',
    'Sailu',
    'Murtijapur',
    'Tasgaon',
    'Mehkar',
    'Yawal',
    'Pulgaon',
    'Nilanga',
    'Wai',
    'Umarga',
    'Paithan',
    'Rahuri',
    'Nawapur',
    'Tuljapur',
    'Morshi',
    'Purna',
    'Satana',
    'Pathri',
    'Sinnar',
    'Uchgaon',
    'Uran',
    'Pen',
    'Karjat',
    'Manwath',
    'Partur',
    'Sangole',
    'Mangrulpir',
    'Risod',
    'Shirur',
    'Savner',
    'Sasvad',
    'Pandharkaoda',
    'Talode',
    'Shrigonda',
    'Shirdi',
    'Raver',
    'Mukhed',
    'Rajura',
    'Vadgaon Kasba',
    'Tirora',
    'Mahad',
    'Lonar',
    'Sawantwadi',
    'Pathardi',
    'Pauni',
    'Ramtek',
    'Mul',
    'Soyagaon',
    'Mangalvedhe',
    'Narkhed',
    'Shendurjana',
    'Patur',
    'Mhaswad',
    'Loha',
    'Nandgaon',
    'Warud',
  ],
  Goa: ['Marmagao', 'Panaji', 'Margao', 'Mapusa'],
  'West Bengal': [
    'Kolkata',
    'Siliguri',
    'Asansol',
    'Raghunathganj',
    'Kharagpur',
    'Naihati',
    'English Bazar',
    'Baharampur',
    'Hugli-Chinsurah',
    'Raiganj',
    'Jalpaiguri',
    'Santipur',
    'Balurghat',
    'Medinipur',
    'Habra',
    'Ranaghat',
    'Bankura',
    'Nabadwip',
    'Darjiling',
    'Purulia',
    'Arambagh',
    'Tamluk',
    'AlipurdUrban Agglomerationr',
    'Suri',
    'Jhargram',
    'Gangarampur',
    'Rampurhat',
    'Kalimpong',
    'Sainthia',
    'Taki',
    'Murshidabad',
    'Memari',
    'Paschim Punropara',
    'Tarakeswar',
    'Sonamukhi',
    'PandUrban Agglomeration',
    'Mainaguri',
    'Malda',
    'Panchla',
    'Raghunathpur',
    'Mathabhanga',
    'Monoharpur',
    'Srirampore',
    'Adra',
  ],
};
